//
//  AuthorizationPresenter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 2.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthorizationPresentationLogic {
	func presentAuthorized(response: Authorization.Something.Response)
}

class AuthorizationPresenter: AuthorizationPresentationLogic {
	weak var viewController: AuthorizationDisplayLogic?

	// MARK: Do something

	func presentAuthorized(response: Authorization.Something.Response) {
		let viewModel = Authorization.Something.ViewModel()
		viewController?.displayAuthorized(viewModel: viewModel)
	}
}
