//
//  AuthorizationModels.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 2.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Authorization {
	// MARK: Use cases
	
	enum Something
	{
		struct Request {
			var email: String
			var passward: String
		}
		struct Response {
		}
		struct ViewModel {
		}
	}
}
