//
//  ReadyToFinishTripViewController.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 28.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReadyToFinishTripDisplayLogic: class {
	func displayResult(viewModel: ReadyToFinishTrip.Something.ViewModel)
}

class ReadyToFinishTripViewController: UIViewController, ReadyToFinishTripDisplayLogic {
	var interactor: ReadyToFinishTripBusinessLogic?
	var router: (NSObjectProtocol & ReadyToFinishTripRoutingLogic & ReadyToFinishTripDataPassing)?

	// MARK: Object lifecycle

	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}

	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}

	// MARK: Setup

	private func setup() {
		let viewController = self
		let interactor = ReadyToFinishTripInteractor()
		let presenter = ReadyToFinishTripPresenter()
		let router = ReadyToFinishTripRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}

	// MARK: Routing

	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}

	// MARK: View lifecycle

	override func viewDidLoad() {
		super.viewDidLoad()
		timeLable.text = trip?.time
		title = trip?.locationName
		tripImage.image = UIImage(named: "back1")
	}

	// MARK: Do something
	var trip: NewTrip?
	@IBOutlet weak var tripImage: UIImageView!
	@IBOutlet weak var timeLable: UILabel!
	@IBOutlet weak var participantsCollection: UICollectionView!

	@IBAction func finishTripAction(_ sender: Any) {
		router?.routeToSaveTripViewController()
	}

	@IBAction func dontWantToParticipateAction(_ sender: Any) {
		let request = ReadyToFinishTrip.Something.Request(trip: trip!)
		print(trip?.document)
		interactor?.removeParticipant(request: request)
	}

	@IBAction func openChatAction(_ sender: Any) {
		router?.routeToChatViewController()
	}


	func displayResult(viewModel: ReadyToFinishTrip.Something.ViewModel) {
		if viewModel.result == nil {
			router?.routeToProfileViewController(source: self)
		}
		else {
			print(viewModel.result)
		}
	}
}
