//
//  ReadyToFinishTripInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 28.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReadyToFinishTripBusinessLogic {
	func removeParticipant(request: ReadyToFinishTrip.Something.Request)
	func loadParticipants(request: ReadyToFinishTrip.Something.Request)
	func setUser(request: ReadyToFinishTrip.Something.Request)
}

protocol ReadyToFinishTripDataStore {
	var trip: NewTrip? { get set }
	var user: FullInformationAppUser? { get set }
}

class ReadyToFinishTripInteractor: ReadyToFinishTripBusinessLogic, ReadyToFinishTripDataStore {
	var presenter: ReadyToFinishTripPresentationLogic?
	var worker: ReadyToFinishTripWorker?
	var trip: NewTrip?
	var user: FullInformationAppUser? 
	
	// MARK: Do something
	
	func removeParticipant(request: ReadyToFinishTrip.Something.Request) {
		worker = ReadyToFinishTripWorker()
		worker?.doSomeWork()
		guard let trip = request.trip else {
			return
		}
		FirebaseDatabaseManager.shered.deleteParticipantFromTrip(with: trip) { [weak self] result in
			let response = ReadyToFinishTrip.Something.Response(result: result)
			self?.presenter?.presentResult(response: response)
		}
	}
	
	func loadParticipants(request: ReadyToFinishTrip.Something.Request) {
		guard let trip = request.trip else {
			return
		}
		FirebaseDatabaseManager.shered.fetchParticipants(collection: "\(trip.region)Trips", document: "\(trip.locationOfParticipants)", secondCollection: "participants", field: "participant") { [weak self] users in
			let response = ReadyToFinishTrip.Something.Response(participants: users)
			self?.presenter?.presentParticipants(response: response)
		}
	}
	
	func setUser(request: ReadyToFinishTrip.Something.Request) {
		user = request.user
		self.presenter?.routeToUserViewController()
	}
	
}
