//
//  ReadyToFinishTripInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 28.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReadyToFinishTripBusinessLogic {
	func removeParticipant(request: ReadyToFinishTrip.Something.Request)
}

protocol ReadyToFinishTripDataStore {
	var trip: NewTrip? { get set }
}

class ReadyToFinishTripInteractor: ReadyToFinishTripBusinessLogic, ReadyToFinishTripDataStore {
	var presenter: ReadyToFinishTripPresentationLogic?
	var worker: ReadyToFinishTripWorker?
	var trip: NewTrip?

	// MARK: Do something

	func removeParticipant(request: ReadyToFinishTrip.Something.Request) {
		worker = ReadyToFinishTripWorker()
		worker?.doSomeWork()
		FirebaseDatabaseManager.shered.deleteParticipantFromTrip(with: request.trip) { [weak self] result in
			let response = ReadyToFinishTrip.Something.Response(result: result)
			self?.presenter?.presentResult(response: response)
		}
	}
	
}
