//
//  CreateTripInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateTripBusinessLogic
{
  func doSomething(request: CreateTrip.Something.Request)
}

protocol CreateTripDataStore
{
  //var name: String { get set }
}

class CreateTripInteractor: CreateTripBusinessLogic, CreateTripDataStore
{
  var presenter: CreateTripPresentationLogic?
  var worker: CreateTripWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CreateTrip.Something.Request)
  {
    worker = CreateTripWorker()
    worker?.doSomeWork()
    
    let response = CreateTrip.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
