//
//  CreateTripRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateTripRoutingLogic {
	func routeToMainViewController()
}

protocol CreateTripDataPassing {
	var dataStore: CreateTripDataStore? { get }
}

class CreateTripRouter: NSObject, CreateTripRoutingLogic, CreateTripDataPassing {
	weak var viewController: CreateTripViewController?
	var dataStore: CreateTripDataStore?

	// MARK: Routing

	func routeToMainViewController() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "MainViewController") as? MainViewController
		destinationVC?.regionName = dataStore?.region ?? "MinskRegion"
		var destinationDS = destinationVC?.router!.dataStore!
		passDataToMainviewController(source: dataStore!, destination: &destinationDS!)
		navigateToMainviewController(source: viewController!, destination: destinationVC!)
	}

	// MARK: Navigation

	func navigateToMainviewController(source: CreateTripViewController, destination: MainViewController) {
		source.show(destination, sender: nil)
	}

	// MARK: Passing data

	func passDataToMainviewController(source: CreateTripDataStore, destination: inout MainDataStore) {
		destination.region = source.region ?? "MinskRegion"
	}
}
