//
//  ProfileModels.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Profile {
  // MARK: Use cases
  
  enum Something {
    struct Request {
		var image: UIImage?
		var name: String?
		var finishedTrip: NewTrip?
		var upcomingTrip: NewTrip?
    }
    struct Response {
		var person: FirebaseAuthManager.FullInformationAppUser?
		var image: UIImage?
		var upcomingTrips: [NewTrip]?
		var finishedTrips: [NewTrip]?
    }
    struct ViewModel {
		var name: String?
		var lastName: String?
		var defaultLocation: String?
		var numberOfTripsOfUser: String?
		var newImage: UIImage?
		var upcomingTrips: [NewTrip]?
		var finishedTrips: [NewTrip]?
    }
  }
}
