//
//  UpcomingTripInformationInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingTripInformationBusinessLogic
{
  func doSomething(request: UpcomingTripInformation.Something.Request)
}

protocol UpcomingTripInformationDataStore
{
  //var name: String { get set }
}

class UpcomingTripInformationInteractor: UpcomingTripInformationBusinessLogic, UpcomingTripInformationDataStore
{
  var presenter: UpcomingTripInformationPresentationLogic?
  var worker: UpcomingTripInformationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UpcomingTripInformation.Something.Request)
  {
    worker = UpcomingTripInformationWorker()
    worker?.doSomeWork()
    
    let response = UpcomingTripInformation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
