//
//  UpcomingTripInformationViewController.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingTripInformationDisplayLogic: class {
  func displaySomething(viewModel: UpcomingTripInformation.Something.ViewModel)
}

class UpcomingTripInformationViewController: UIViewController, UpcomingTripInformationDisplayLogic {
  var interactor: UpcomingTripInformationBusinessLogic?
  var router: (NSObjectProtocol & UpcomingTripInformationRoutingLogic & UpcomingTripInformationDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let viewController = self
    let interactor = UpcomingTripInformationInteractor()
    let presenter = UpcomingTripInformationPresenter()
    let router = UpcomingTripInformationRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad() {
		super.viewDidLoad()
		locationTitle.title = tripInformation?.locationName
		locationImage.image = UIImage(named: "back1")
		tripStartPlace.text = tripInformation?.description
		tripTime.text = tripInformation?.time
		doSomething()
	}
  
  // MARK: Do something
	var tripInformation: NewTrip?

	@IBOutlet weak var locationTitle: UINavigationItem!
	@IBOutlet weak var locationImage: UIImageView!
	@IBOutlet weak var tripStartPlace: UILabel!
	@IBOutlet weak var tripTime: UILabel!
	@IBOutlet weak var whoPacticipateCollection: UICollectionView!
	@IBAction func chatButtonAction(_ sender: Any) {
	}
	
	func doSomething() {
    let request = UpcomingTripInformation.Something.Request()
    interactor?.doSomething(request: request)

  }
  
  func displaySomething(viewModel: UpcomingTripInformation.Something.ViewModel) {
    //nameTextField.text = viewModel.name
  }
}
