//
//  UpcomingTripInformationPresenter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingTripInformationPresentationLogic
{
  func presentParticipants(response: UpcomingTripInformation.Something.Response)
	func routeToUserViewController()
}

class UpcomingTripInformationPresenter: UpcomingTripInformationPresentationLogic
{
  weak var viewController: UpcomingTripInformationDisplayLogic?
  
  // MARK: Do something
  
  func presentParticipants(response: UpcomingTripInformation.Something.Response)
  {
	  let viewModel = UpcomingTripInformation.Something.ViewModel(users: response.users)
    viewController?.displayUsers(viewModel: viewModel)
  }

	func routeToUserViewController() {
		viewController?.displayUserViewController()
	}
}
