//
//  UpcomingTripInformationRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UpcomingTripInformationRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
	func routeToUserViewController()
}

protocol UpcomingTripInformationDataPassing
{
  var dataStore: UpcomingTripInformationDataStore? { get }
}

class UpcomingTripInformationRouter: NSObject, UpcomingTripInformationRoutingLogic, UpcomingTripInformationDataPassing
{
  weak var viewController: UpcomingTripInformationViewController?
  var dataStore: UpcomingTripInformationDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: UpcomingTripInformationViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: UpcomingTripInformationDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}

	func routeToUserViewController() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "OtherUserViewController") as! OtherUserViewController
		destinationVC.user = dataStore?.user
		var destinationDS = destinationVC.router!.dataStore!
		passDataToUser(source: dataStore!, destination: &destinationDS)
		navigateToUserViewController(source: viewController!, destination: destinationVC)
	}

	// MARK: Navigation

	func navigateToUserViewController(source: UpcomingTripInformationViewController, destination: OtherUserViewController) {
		source.show(destination, sender: nil)
	}

	// MARK: Passing data

	func passDataToUser(source: UpcomingTripInformationDataStore, destination: inout OtherUserDataStore) {
		destination.user = source.user
	}
}
