//
//  SelectedPlaceInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectedPlaceBusinessLogic
{
  func doSomething(request: SelectedPlace.Something.Request)
}

protocol SelectedPlaceDataStore
{
  //var name: String { get set }
}

class SelectedPlaceInteractor: SelectedPlaceBusinessLogic, SelectedPlaceDataStore
{
  var presenter: SelectedPlacePresentationLogic?
  var worker: SelectedPlaceWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SelectedPlace.Something.Request)
  {
    worker = SelectedPlaceWorker()
    worker?.doSomeWork()
    
    let response = SelectedPlace.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
