//
//  SelectedPlaceInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectedPlaceBusinessLogic {
  func addToFavorite(request: SelectedPlace.Something.Request)
}

protocol SelectedPlaceDataStore {
  var location: Location? { get set }
}

class SelectedPlaceInteractor: SelectedPlaceBusinessLogic, SelectedPlaceDataStore {
  var presenter: SelectedPlacePresentationLogic?
  var worker: SelectedPlaceWorker?
  var location: Location?
  
  // MARK: Do something
  
  func addToFavorite(request: SelectedPlace.Something.Request) {
    worker = SelectedPlaceWorker()
    worker?.doSomeWork()

	  FirebaseDatabaseManager.shered.addFavoriteToDatabase(location: request.location, complition: {
		 [weak self] result in
		  if result == true {
			  let response = SelectedPlace.Something.Response(result: "Added")
			  self?.presenter?.presentResult(response: response)
		  }
		  else {
			  let response = SelectedPlace.Something.Response(result: "Error")
			  self?.presenter?.presentResult(response: response)
		  }
	  })
  }
}
