//
//  MainInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 10.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol MainBusinessLogic {
	func loadInformation(request: Main.Something.Request)
	func setPopularLocation(request: Main.Something.Request)
	func loadCreatedTrips(request: Main.Something.Request)
	func loadPins(request: Main.Something.Request)
	func setNewTripInformation(request: Main.Something.Request)
}

protocol MainDataStore {
	var region: String { get set }
	var selectedPopularlocation: Location? { get set }
	var newTrip: NewTrip? { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
	var presenter: MainPresentationLogic?
	var worker: MainWorker?
	var region: String = ""
	var selectedPopularlocation: Location?
	var newTrip: NewTrip?
	// MARK: Do something

	func loadInformation(request: Main.Something.Request) {
		worker = MainWorker()
		worker?.doSomeWork()
		region = request.region

		FirebaseDatabaseManager.shered.fetchLocationData(collection: request.region) { [weak self] locations in

			let popular = locations.filter { location in
				location.isPopular == true
			}
			let response = Main.Something.Response(locations: popular)
			self?.presenter?.presentPopularPlaces(response: response)
		}
	}

	func setPopularLocation(request: Main.Something.Request) {
		selectedPopularlocation = request.selectedPopularPlace
		self.presenter?.presentSelectedPopularlocation()
	}

	func setNewTripInformation(request: Main.Something.Request) {
		newTrip = request.newTrip
		self.presenter?.presentNewTripInformation()
	}


	func loadCreatedTrips(request: Main.Something.Request) {
		FirebaseDatabaseManager.shered.fetchCreatedTrips(collection: request.region) { [weak self] new  in
			let response = Main.Something.Response(locations: nil, new: new)
			self?.presenter?.presentCreatedTrips(response: response)
		}
	}
	
	func loadPins(request: Main.Something.Request) {
		FirebaseDatabaseManager.shered.fetchLocationData(collection: request.region) { [weak self] locations in
			guard let location = locations.last else {
				return
			}
			let loc = CLLocationCoordinate2D(latitude: location.lat, longitude: location.lng)
			let response = Main.Something.Response(location: MapPinAnnotation(title: location.name, location: location, coordinate: loc))
			self?.presenter?.presentPins(response: response)
		}
	}
}
