//
//  MainRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 10.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic
{
  func routeToAllLocationsViewController()
	func routeToSelectedPlaceViewController()
	func routeToUpcomingTripViewController()
}

protocol MainDataPassing
{
  var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
	weak var viewController: MainViewController?
	var dataStore: MainDataStore?

	// MARK: Routing

	func routeToAllLocationsViewController() {

		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "AllLocationsViewController") as! AllLocationsViewController
		destinationVC.region = dataStore?.region
		var destinationDS = destinationVC.router!.dataStore!
		passDataToAllLocationsViewController(source: dataStore!, destination: &destinationDS)
		navigateToAllLocationsViewController(source: viewController!, destination: destinationVC)
	}

	// MARK: Navigation

	func navigateToAllLocationsViewController(source: MainViewController, destination: AllLocationsViewController) {
		source.navigationController?.pushViewController(destination, animated: true)
	}

	// MARK: Passing data

	func passDataToAllLocationsViewController(source: MainDataStore, destination: inout AllLocationsDataStore) {
		destination.region = source.region
	}

	func routeToSelectedPlaceViewController() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "SelectedPlaceViewController") as! SelectedPlaceViewController
		destinationVC.location = dataStore?.selectedPopularlocation
		destinationVC.region = dataStore?.region
		var destinationDS = destinationVC.router!.dataStore!
		passDataToSelectedPlaceViewcontroller(source: dataStore!, destination: &destinationDS)
		navigateToSelectedPlaceViewcontroller(source: viewController!, destination: destinationVC)
	}

	// MARK: Navigation

	func navigateToSelectedPlaceViewcontroller(source: MainViewController, destination: SelectedPlaceViewController) {
		source.navigationController?.pushViewController(destination, animated: true)
	}

	// MARK: Passing data

	func passDataToSelectedPlaceViewcontroller(source: MainDataStore, destination: inout SelectedPlaceDataStore) {
		destination.location = source.selectedPopularlocation
		destination.region = source.region
	}

	func routeToUpcomingTripViewController() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "UpcomingTripInformationViewController") as! UpcomingTripInformationViewController
		destinationVC.tripInformation = dataStore?.newTrip
		var destinationDS = destinationVC.router!.dataStore!
		passDataToUpcomingTripViewController(source: dataStore!, destination: &destinationDS)
		navigateToUpcomingTripViewController(source: viewController!, destination: destinationVC)
	}

	// MARK: Navigation

	func navigateToUpcomingTripViewController(source: MainViewController, destination: UpcomingTripInformationViewController) {
		source.navigationController?.pushViewController(destination, animated: true)
	}

	// MARK: Passing data

	func passDataToUpcomingTripViewController(source: MainDataStore, destination: inout UpcomingTripInformationDataStore) {
		destination.newTrip = source.newTrip
	}
}
