//
//  MainInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 10.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
  func loadInformation(request: Main.Something.Request)
	func setPopularLocation(request: Main.Something.Request)
	func loadCreatedTrips(request: Main.Something.Request)
}

protocol MainDataStore {
  var region: String { get set }
	var selectedPopularlocation: Location? { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
  var presenter: MainPresentationLogic?
  var worker: MainWorker?
  var region: String = ""
	var selectedPopularlocation: Location?
  // MARK: Do something
  
  func loadInformation(request: Main.Something.Request) {
		worker = MainWorker()
		worker?.doSomeWork()
		region = request.region

		FirebaseDatabaseManager.shered.fetchLocationData(collection: request.region) { [weak self] locations in
			let response = Main.Something.Response(locations: locations)
			self?.presenter?.presentPopularPlaces(response: response)
		}
	}

	func setPopularLocation(request: Main.Something.Request) {
		selectedPopularlocation = request.selectedPopularPlace
		self.presenter?.presentSelectedPopularlocation()
	}

	func loadCreatedTrips(request: Main.Something.Request) {
		FirebaseDatabaseManager.shered.fetchCreatedTrips(collection: request.region) { [weak self] new in
			let response = Main.Something.Response(locations: nil, new: new)
			self?.presenter?.presentCreatedTrips(response: response)
		}
	}
}
