//
//  SliderRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 2.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SliderRoutingLogic {
	func routeToRegister()
	func routeToAuthorization()
}

protocol SliderDataPassing {
	var dataStore: SliderDataStore? { get }
}

class SliderRouter: NSObject, SliderRoutingLogic, SliderDataPassing {
	weak var viewController: SliderViewController?
	var dataStore: SliderDataStore?
	
	// MARK: Routing
	
	func routeToRegister() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "RegistrationViewController") as? RegistrationViewController
		destinationVC?.modalPresentationStyle = .fullScreen
		navigateToRegistrationViewController(source: viewController!, destination: destinationVC!)
	}
	
	func routeToAuthorization() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "AuthorizationViewController") as? AuthorizationViewController
		destinationVC?.modalPresentationStyle = .fullScreen
		navigateToAuthorizationViewController(source: viewController!, destination: destinationVC!)
	}
	
	// MARK: Navigation
	
	func navigateToRegistrationViewController(source: SliderViewController, destination: RegistrationViewController) {
		source.show(destination, sender: nil)
	}
	
	func navigateToAuthorizationViewController(source: SliderViewController, destination: AuthorizationViewController) {
		source.show(destination, sender: nil)
	}
}
