//
//  SliderInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 2.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SliderBusinessLogic
{
  func doSomething(request: Slider.Something.Request)
}

protocol SliderDataStore
{
  //var name: String { get set }
}

class SliderInteractor: SliderBusinessLogic, SliderDataStore
{
  var presenter: SliderPresentationLogic?
  var worker: SliderWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Slider.Something.Request)
  {
    worker = SliderWorker()
    worker?.doSomeWork()
    
    let response = Slider.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
