//
//  SliderPresenter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 2.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SliderPresentationLogic {
	func presentSomething(response: Slider.Something.Response)
}

class SliderPresenter: SliderPresentationLogic {
	weak var viewController: SliderDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: Slider.Something.Response) {
		let firstPage = Slider.Something.ViewModel(id: 1, lable: "BelTravelApp", image: UIImage(named: "back1")!)
		let secondPage = Slider.Something.ViewModel(id: 2, lable: "Registration...", image: UIImage(named: "back2")!)
		let viewModel = [firstPage, secondPage]
		viewController?.updateyCollectionView(viewModel: viewModel)
	}
}
