//
//  ChatListPresenter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 26.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatListPresentationLogic
{
  func presentSomething(response: ChatList.Something.Response)
}

class ChatListPresenter: ChatListPresentationLogic
{
  weak var viewController: ChatListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ChatList.Something.Response)
  {
    let viewModel = ChatList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
