//
//  SelectedTripInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectedTripBusinessLogic
{
  func doSomething(request: SelectedTrip.Something.Request)
}

protocol SelectedTripDataStore
{
  //var name: String { get set }
}

class SelectedTripInteractor: SelectedTripBusinessLogic, SelectedTripDataStore
{
  var presenter: SelectedTripPresentationLogic?
  var worker: SelectedTripWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SelectedTrip.Something.Request)
  {
    worker = SelectedTripWorker()
    worker?.doSomeWork()
    
    let response = SelectedTrip.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
