//
//  SelectedTripPresenter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectedTripPresentationLogic {
	func presentImages(response: SelectedTrip.Something.Response)
	func presentParticipants(response: SelectedTrip.Something.Response)
}

class SelectedTripPresenter: SelectedTripPresentationLogic {
	weak var viewController: SelectedTripDisplayLogic?

	// MARK: Do something

	func presentImages(response: SelectedTrip.Something.Response) {
		let viewModel = SelectedTrip.Something.ViewModel(images: response.images)
		viewController?.displayPhotos (viewModel: viewModel)
	}

	func presentParticipants(response: SelectedTrip.Something.Response) {
		let viewModel = SelectedTrip.Something.ViewModel(users: response.users)
		viewController?.displayParticipants (viewModel: viewModel)
	}
}
