//
//  SelectedTripRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SelectedTripRoutingLogic {
}

protocol SelectedTripDataPassing {
	var dataStore: SelectedTripDataStore? { get }
}

class SelectedTripRouter: NSObject, SelectedTripRoutingLogic, SelectedTripDataPassing {
	weak var viewController: SelectedTripViewController?
	var dataStore: SelectedTripDataStore?

}
