//
//  AllLocationsRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 16.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AllLocationsRoutingLogic
{
  func routeToSelectedPlaceViewcontroller()
}

protocol AllLocationsDataPassing
{
  var dataStore: AllLocationsDataStore? { get }
}

class AllLocationsRouter: NSObject, AllLocationsRoutingLogic, AllLocationsDataPassing
{
  weak var viewController: AllLocationsViewController?
  var dataStore: AllLocationsDataStore?
  
  // MARK: Routing
  
  func routeToSelectedPlaceViewcontroller() {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SelectedPlaceViewController") as! SelectedPlaceViewController
	  destinationVC.location = dataStore?.location
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: AllLocationsViewController, destination: SelectedPlaceViewController) {
	  source.navigationController?.pushViewController(destination, animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: AllLocationsDataStore, destination: inout SelectedPlaceDataStore)
  {
	  destination.location = source.location
  }
}
