//
//  AllLocationsInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 16.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllLocationsBusinessLogic {
  func loadLocation(request: AllLocations.Something.Request)
}

protocol AllLocationsDataStore {
	var region: String { get set }
}

class AllLocationsInteractor: AllLocationsBusinessLogic, AllLocationsDataStore {

  var presenter: AllLocationsPresentationLogic?
  var worker: AllLocationsWorker?
	var region: String = ""
  
  // MARK: Do something
  
  func loadLocation(request: AllLocations.Something.Request) {
    worker = AllLocationsWorker()
    worker?.doSomeWork()
	  region = request.region
	  FirebaseDatabaseManager.shered.fetchLocationData(collection: request.region) { [weak self] locations in
		  let response = AllLocations.Something.Response(locations: locations)
		  self?.presenter?.presentLocations(response: response)
	  }
  }
}
