//
//  AllLocationsModels.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 16.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AllLocations {
  // MARK: Use cases
  
  enum Something {
    struct Request {
		var region: String?
		var location: Location?
    }
	  struct Response {
		  var locations: [Location]
	  }
    struct ViewModel {
		var locations: [Location]
    }
  }
}
