//
//  AllLocationsPresenter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 16.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllLocationsPresentationLogic {
  func presentLocations(response: AllLocations.Something.Response)
}

class AllLocationsPresenter: AllLocationsPresentationLogic {
  weak var viewController: AllLocationsDisplayLogic?
  
  // MARK: Do something
  
  func presentLocations(response: AllLocations.Something.Response) {
	  let viewModel = AllLocations.Something.ViewModel(locations: response.locations)
	  viewController?.presentLocationsInSelectedRegion(viewModel: viewModel)
  }
}
