//
//  SaveTripRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 28.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SaveTripRoutingLogic {
	func routeToProfile(source: SaveTripViewController)
}

protocol SaveTripDataPassing {
	var dataStore: SaveTripDataStore? { get }
}

class SaveTripRouter: NSObject, SaveTripRoutingLogic, SaveTripDataPassing {
	weak var viewController: SaveTripViewController?
	var dataStore: SaveTripDataStore?

	// MARK: Routing
	func routeToProfile(source: SaveTripViewController) {
		source.navigationController?.popToRootViewController(animated: true)
	}

}
