//
//  OtherUserRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 25.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OtherUserRoutingLogic
{
	func routeToSelectedFinishedTripViewController()
}

protocol OtherUserDataPassing
{
  var dataStore: OtherUserDataStore? { get }
}

class OtherUserRouter: NSObject, OtherUserRoutingLogic, OtherUserDataPassing
{
  weak var viewController: OtherUserViewController?
  var dataStore: OtherUserDataStore?
  
	func routeToSelectedFinishedTripViewController() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "SelectedTripViewController") as! SelectedTripViewController
		destinationVC.trip = dataStore?.finishedTrip

		destinationVC.modalPresentationStyle = .fullScreen
		var destinationDS = destinationVC.router!.dataStore!
		passDataToSomewhere(source: dataStore!, destination: &destinationDS)
		navigateToSomewhere(source: viewController!, destination: destinationVC)
	}

	// MARK: Navigation

	func navigateToSomewhere(source: OtherUserViewController, destination: SelectedTripViewController) {
		let nav = UINavigationController(rootViewController: destination)
		nav.modalPresentationStyle = .automatic
		if let sheet = nav.sheetPresentationController {
			sheet.detents = [.medium(), .large()]
		}
		source.present(nav, animated: true)
	}

	// MARK: Passing data

	func passDataToSomewhere(source: OtherUserDataStore, destination: inout SelectedTripDataStore) {
		destination.trip = source.finishedTrip
	}
}
