//
//  OtherUserModels.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 25.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OtherUser {
	// MARK: Use cases

	enum Something {
		struct Request {
			var user: FullInformationAppUser?
			var finishedTrip: NewTrip?
		}
		struct Response {
			var upcomingTrips: [NewTrip]?
			var finishedTrips: [NewTrip]?
		}
		struct ViewModel {
			var upcomingTrips: [NewTrip]?
			var finishedTrips: [NewTrip]?
		}
	}
}
