//
//  OtherUserInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 25.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OtherUserBusinessLogic {
  func setUserInfo(request: OtherUser.Something.Request)
}

protocol OtherUserDataStore {
	var user: FirebaseAuthManager.FullInformationAppUser? { get set }
}

class OtherUserInteractor: OtherUserBusinessLogic, OtherUserDataStore {
	var presenter: OtherUserPresentationLogic?
	var worker: OtherUserWorker?
	var user: FirebaseAuthManager.FullInformationAppUser?

	// MARK: Do something

	func setUserInfo(request: OtherUser.Something.Request) {
		worker = OtherUserWorker()
		worker?.doSomeWork()
		let response = OtherUser.Something.Response()
		presenter?.presentUserInformation(response: response)
	}
}
