//
//  OtherUserPresenter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 25.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OtherUserPresentationLogic
{
  func presentUserInformation(response: OtherUser.Something.Response)
}

class OtherUserPresenter: OtherUserPresentationLogic
{
  weak var viewController: OtherUserDisplayLogic?
  
  // MARK: Do something
  
  func presentUserInformation(response: OtherUser.Something.Response)
  {
    let viewModel = OtherUser.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
