//
//  RegistrationViewController.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 2.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationDisplayLogic: class {
  func displaySomething(viewModel: Registration.Something.ViewModel)
}

class RegistrationViewController: UIViewController, RegistrationDisplayLogic {
	var interactor: RegistrationBusinessLogic?
	var router: (NSObjectProtocol & RegistrationRoutingLogic & RegistrationDataPassing)?
	let checkField = CheckField.shared
	// MARK: Object lifecycle

	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}

	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}

	// MARK: Setup

	private func setup() {
		let viewController = self
		let interactor = RegistrationInteractor()
		let presenter = RegistrationPresenter()
		let router = RegistrationRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}

	// MARK: Routing

	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}

	// MARK: View lifecycle

	override func viewDidLoad() {
		super.viewDidLoad()
		photoGesture = UITapGestureRecognizer(target: self, action: #selector(addPhoto))
		photoOutlet.isUserInteractionEnabled = true
		photoOutlet.addGestureRecognizer(photoGesture!)
		tapGesture = UITapGestureRecognizer(target: self, action: #selector(tapped))
		mainView.addGestureRecognizer(tapGesture!)
	}

	// MARK: Do something
	var tapGesture: UITapGestureRecognizer?
	var photoGesture: UITapGestureRecognizer?
	@IBOutlet weak var photoOutlet: UIImageView!
	@IBOutlet weak var mainView: UIView!
	@IBOutlet weak var emailView: UIView!
	@IBOutlet weak var passwordView: UIView!
	@IBOutlet weak var repeatPasswordView: UIView!

	@IBOutlet weak var emailTextField: UITextField!
	@IBOutlet weak var passwordTextField: UITextField!
	@IBOutlet weak var repeatPasswordTextField: UITextField!
	@IBOutlet weak var nameTextField: UITextField!
	@IBOutlet weak var lastNameTextField: UITextField!
	@IBOutlet weak var defaultLocationTextField: UITextField!
	
	@objc func tapped() {
		self.view.endEditing(true)
	}

	@objc func addPhoto() {
	presentPhoto()
	}

	func displaySomething(viewModel: Registration.Something.ViewModel) {
		router?.routeToTabBarViewController()
	}

	@IBAction func registrationButtonAction(_ sender: UIButton) {
		if !nameTextField.text!.isEmpty && !lastNameTextField.text!.isEmpty && !defaultLocationTextField.text!.isEmpty {
		guard let name = nameTextField.text else {return}
		guard let lastName = lastNameTextField.text else {return}
		guard let defaultLocation = defaultLocationTextField.text else {return}
		if checkField.validField(emailView, emailTextField),
		   checkField.validField(passwordView, passwordTextField) {
			if passwordTextField.text == repeatPasswordTextField.text {
				let request = Registration.Something.Request(email: emailTextField.text ?? "", passward: passwordTextField.text ?? "", name: name, lastName: lastName, defaultLocation: defaultLocation, image: photoOutlet.image)
				interactor?.createNewUser(request: request)
			}
		}
	}
	}

	@IBAction func closeButtonAction(_ sender: UIButton) {
		self.dismiss(animated: true)
	}
}



extension RegistrationViewController: UIImagePickerControllerDelegate, UINavigationControllerDelegate {

	func photoWithCamera(){
		let vc = UIImagePickerController()
		vc.sourceType = .camera
		vc.delegate = self
		vc.allowsEditing = true
		present(vc, animated: true)
	}
	func photoFromLibrary(){
		let vc = UIImagePickerController()
		vc.sourceType = .photoLibrary
		vc.delegate = self
		vc.allowsEditing = true
		present(vc, animated: true)
	}

	func presentPhoto(){
		let choose = UIAlertController(title: "Profile Photo", message: "How would you like to select a photo?", preferredStyle: .actionSheet)
		let library = UIAlertAction(title: "photo library", style: .default, handler: {[weak self] _ in self?.photoFromLibrary() } )
		let camera = UIAlertAction(title: "take photo", style: .default, handler: {[weak self] _ in self?.photoWithCamera()} )
		let cancel = UIAlertAction(title: "cancel", style: .cancel, handler: nil)
		choose.addAction(library)
		choose.addAction(camera)
		choose.addAction(cancel)
		present(choose, animated: true)
	}

	func imagePickerController (_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any] ) {
		picker.dismiss(animated: true, completion: nil)
		guard  let selectedImage = info[UIImagePickerController.InfoKey.editedImage] as? UIImage else {
			return
		}
		photoOutlet.image = selectedImage
	}
	func imagePickerControllerDidCancel(_ picker: UIImagePickerController) {
		picker.dismiss(animated: true, completion: nil)
	}
}
