//
//  RegistrationViewController.swift
//  Messenger
//
//  Created by Tatsiana Marchanka on 2.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationDisplayLogic: class {
  func displaySomething(viewModel: Registration.Something.ViewModel)
}

class RegistrationViewController: UIViewController, RegistrationDisplayLogic {
	var interactor: RegistrationBusinessLogic?
	var router: (NSObjectProtocol & RegistrationRoutingLogic & RegistrationDataPassing)?
	let checkField = CheckField.shared
	// MARK: Object lifecycle

	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}

	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}

	// MARK: Setup

	private func setup() {
		let viewController = self
		let interactor = RegistrationInteractor()
		let presenter = RegistrationPresenter()
		let router = RegistrationRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}

	// MARK: Routing

	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}

	// MARK: View lifecycle

	override func viewDidLoad() {
		super.viewDidLoad()
		tapGesture = UITapGestureRecognizer(target: self, action: #selector(tapped))
		mainView.addGestureRecognizer(tapGesture!)
	}

	// MARK: Do something
	var tapGesture: UITapGestureRecognizer?
	@IBOutlet weak var mainView: UIView!
	@IBOutlet weak var emailView: UIView!
	@IBOutlet weak var passwordView: UIView!
	@IBOutlet weak var repeatPasswordView: UIView!

	@IBOutlet weak var emailTextField: UITextField!
	@IBOutlet weak var passwordTextField: UITextField!
	@IBOutlet weak var repeatPasswordTextField: UITextField!

	@objc func tapped() {
		self.view.endEditing(true)
	}

	func displaySomething(viewModel: Registration.Something.ViewModel) {
		router?.routeToMessengerTabBarViewController()
	}

	@IBAction func registrationButtonAction(_ sender: UIButton) {
		if checkField.validField(emailView, emailTextField),
		   checkField.validField(passwordView, passwordTextField) {
			if passwordTextField.text == repeatPasswordTextField.text {
				let request = Registration.Something.Request(email: emailTextField.text ?? "", passward: passwordTextField.text ?? "")
				interactor?.createNewUser(request: request)
			}
		}
	}

	@IBAction func closeButtonAction(_ sender: UIButton) {
		self.dismiss(animated: true)
	}
}
