//
//  FavoriteRouter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoriteRoutingLogic {
	func routeToSelectedPlaceViewController()
}

protocol FavoriteDataPassing {
	var dataStore: FavoriteDataStore? { get }
}

class FavoriteRouter: NSObject, FavoriteRoutingLogic, FavoriteDataPassing {
	weak var viewController: FavoriteViewController?
	var dataStore: FavoriteDataStore?

	// MARK: Routing

	func routeToSelectedPlaceViewController() {
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "SelectedPlaceViewController") as? SelectedPlaceViewController
		destinationVC?.location = dataStore?.location
		destinationVC?.region = dataStore?.region
		var destinationDS = destinationVC?.router!.dataStore!
		passDataToSelectedPlaceViewController(source: dataStore!, destination: &destinationDS!)
		navigateToSelectedPlaceViewController(source: viewController!, destination: destinationVC!)
	}

	// MARK: Navigation

	func navigateToSelectedPlaceViewController(source: FavoriteViewController, destination: SelectedPlaceViewController) {
		source.navigationController?.pushViewController(destination, animated: true)
	}

	// MARK: Passing data

	func passDataToSelectedPlaceViewController(source: FavoriteDataStore, destination: inout SelectedPlaceDataStore) {
		destination.location = source.location
		destination.region = source.region
	}
}
