//
//  FavoritePresenter.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritePresentationLogic
{
  func presentFavoritePlaces(response: Favorite.Something.Response)
	func routeToSelectedPlaceViewController()
}

class FavoritePresenter: FavoritePresentationLogic
{
  weak var viewController: FavoriteDisplayLogic?
  
  // MARK: Do something
  
  func presentFavoritePlaces(response: Favorite.Something.Response)
  {
	  let viewModel = Favorite.Something.ViewModel(locations: response.locations)
	  viewController?.displayFavoriteLocations(viewModel: viewModel)
  }

	func routeToSelectedPlaceViewController() {
		viewController?.displaySelecteTripViewController()
	}
}
