//
//  FavoriteInteractor.swift
//  BelTravelApp
//
//  Created by Tatsiana Marchanka on 11.05.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteBusinessLogic
{
  func loadFavorite(request: Favorite.Something.Request)
}

protocol FavoriteDataStore
{
  //var name: String { get set }
}

class FavoriteInteractor: FavoriteBusinessLogic, FavoriteDataStore
{
  var presenter: FavoritePresentationLogic?
  var worker: FavoriteWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func loadFavorite(request: Favorite.Something.Request)
  {
    worker = FavoriteWorker()
    worker?.doSomeWork()

	  FirebaseDatabaseManager.shered.fetchFavoriteData { [weak self] locations in
		  let response = Favorite.Something.Response(locations: locations)
		  self?.presenter?.presentFavoritePlaces(response: response)
	  }
  }
}
